[package]
name = "pp_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
mio = { version = "1.0.2", features = ["net", "os-poll"] }
pico-args = "0.5.0"
private_poker = { path = "../private_poker" }
ratatui = "0.28.0"
regex = "1.10.6"
whoami = "1.5.2"
